"use client";
import Image from "next/image";
import { Heart, Search, UserRound, ShoppingBag, Sparkles, ArrowRight, Upload, Type, Shapes, Minus, Plus, X, Check, ShieldCheck, Truck, FileCheck2 } from "lucide-react";
import { useState } from "react";
import { categories, collections } from "@/lib/catalog";

type Drawer = "cart" | "favorites" | "profile" | null;
const scroll = (id:string) => document.getElementById(id)?.scrollIntoView({behavior:"smooth"});

export function Storefront(){
  const [drawer,setDrawer]=useState<Drawer>(null); const [cart,setCart]=useState(0); const [fav,setFav]=useState(false);
  const [product,setProduct]=useState("Оверсайз футболка"); const [color,setColor]=useState("Чёрный"); const [scale,setScale]=useState(100); const [side,setSide]=useState("Спереди");
  return <main>
    <header className="header"><a className="brand" href="#"><b>пс</b><span>ПринтСелект</span></a><nav><button onClick={()=>scroll("catalog")}>Каталог⌄</button><button onClick={()=>scroll("constructor")}>Создать принт</button><button onClick={()=>scroll("collections")}>Готовые дизайны</button><button onClick={()=>scroll("wholesale")}>Оптовые партии</button><button onClick={()=>scroll("hobby")}>HOBBY# <i>NEW</i></button><button onClick={()=>scroll("how")}>Как заказать</button></nav><div className="actions"><button aria-label="Поиск"><Search/></button><button aria-label="Избранное" onClick={()=>setDrawer("favorites")}><Heart/></button><button aria-label="Профиль" onClick={()=>setDrawer("profile")}><UserRound/></button><button aria-label={`Корзина, товаров: ${cart}`} onClick={()=>setDrawer("cart")}><ShoppingBag/><em>{cart}</em></button></div></header>
    <section className="hero" aria-label="Твой принт. Твоя вещь. Наше исполнение."><div className="heroCopy"><p className="eyebrow">ПРИНТ, КОТОРЫЙ СТАНОВИТСЯ ВЕЩЬЮ</p><h1>Твой принт.<br/>Твоя вещь.<br/>Наше <span>исполнение.</span></h1><p className="lead">Загрузи изображение, настрой товар под себя — мы проверим макет, согласуем детали и доставим заказ по России.</p><div className="cta"><button className="primary" onClick={()=>scroll("constructor")}><Sparkles/>Создать свой дизайн</button><button className="outline" onClick={()=>scroll("collections")}>Выбрать готовый принт</button></div><button className="textButton" onClick={()=>scroll("wholesale")}>Заказать оптом</button><div className="trust"><span>● Проверка макета</span><span>● Согласование заказа</span><span>● Доставка по России</span></div></div><div className="heroVisual"><Image src="/assets/hero-all-categories.png" alt="Одежда и аксессуары с авторскими принтами" fill priority sizes="(max-width: 800px) 100vw, 50vw"/><div className="price">от <strong>1 490 ₽</strong><small>за готовую вещь</small></div></div></section>
    <section className="steps" id="how">{[["1","Выберите товар","Одежда, посуда и аксессуары"],["2","Добавьте принт","Загрузите или выберите дизайн"],["3","Оформите заказ","Мы проверим и согласуем детали"]].map(s=><article key={s[0]}><b>{s[0]}</b><div><strong>{s[1]}</strong><small>{s[2]}</small></div></article>)}</section>
    <section className="wholesale" id="wholesale"><div><p className="eyebrow lime">ДЛЯ КОМАНД, БРЕНДОВ И МЕРОПРИЯТИЙ</p><h2>Большая партия —<br/>отдельный расчёт</h2><p>От 20 единиц одного или нескольких товаров. Подберём способ печати, производителя, проверим макеты и согласуем образец перед запуском партии.</p><ul><li>Размерный ряд и разные цвета</li><li>Один или несколько макетов</li><li>Доставка одной или несколькими партиями</li></ul><button className="limeButton">Рассчитать оптовую партию <ArrowRight/></button></div><div className="tiers">{[["20–49","Пробная партия","Проверим спрос без большого тиража"],["50–99","Малый опт","Для команд, студий и небольших событий"],["100–299","Оптовая партия","Согласуем образец и график производства"],["300+","Спецусловия","Разделим поставку и подберём производство"]].map(t=><article key={t[0]}><strong>{t[0]}<small> шт.</small></strong><div><b>{t[1]}</b><span>{t[2]}</span></div></article>)}</div></section>
    <section className="catalog section" id="catalog"><div className="sectionHead"><div><p className="eyebrow">КАТАЛОГ</p><h2>Выбери основу<br/>для своего дизайна</h2></div><button className="outline">Смотреть все категории <ArrowRight/></button></div><div className="categoryGrid">{categories.map(([name,price,type],i)=><button className={`cat cat${i}`} key={type} onClick={()=>{setProduct(name.replace("футболки","футболка"));scroll("constructor")}}><div className="mockShape">{type==="mug"?"◯":"✦"}</div><strong>{name}</strong><span>{price}</span></button>)}</div></section>
    <section className="builder section" id="constructor"><p className="eyebrow">ОНЛАЙН-КОНСТРУКТОР</p><h2>Собери вещь, которую хочется носить</h2><p className="sectionIntro">Размести свой файл или выбери готовую основу. Макет сохраняется отдельно от избранного и остаётся доступен в «Моих дизайнах».</p><div className="builderGrid"><aside className="tools"><div className="tabs"><button className="active"><Shapes/>Товар</button><button><Upload/>Фото</button><button><Type/>Текст</button></div><h3>Выберите товар</h3><div className="optionList">{["Оверсайз футболка","Классическая футболка","Худи","Свитшот","Шопер","Кружка","Чехол"].map(x=><button className={product===x?"selected":""} onClick={()=>setProduct(x)} key={x}>{x}</button>)}</div><h3>Цвет товара</h3><div className="swatches">{[["Чёрный","#171419"],["Белый","#eee"],["Графитовый","#4b4a50"],["Бежевый","#d5c1a8"],["Розовый","#d38fa8"],["Тёмно-синий","#12203b"],["Фиолетовый","#6f2d91"]].map(([n,c])=><button aria-label={`Выбрать цвет: ${n}`} title={n} className={color===n?"picked":""} style={{background:c}} onClick={()=>setColor(n)} key={n}/>)}</div><h3>Сторона печати</h3><div className="segmented"><button className={side==="Спереди"?"selected":""} onClick={()=>setSide("Спереди")}>Спереди</button><button className={side==="Сзади"?"selected":""} onClick={()=>setSide("Сзади")}>Сзади</button></div></aside><div className="preview"><div className="previewLabel">{product} · {color.toLowerCase()} · {side.toLowerCase()}</div><Image src="/assets/tshirts/tshirt-black-front.png" alt="Предпросмотр товара" width={700} height={700}/><div className="print" style={{transform:`translate(-50%,-50%) scale(${scale/100})`}}><b>BORN</b><span>TO</span><b>FLY</b><small>HOBBY# / FPV</small></div><div className="zoom"><button onClick={()=>setScale(Math.max(60,scale-10))}><Minus/></button><b>{scale}%</b><button onClick={()=>setScale(Math.min(140,scale+10))}><Plus/></button></div></div><aside className="settings"><p>Настройка принта</p><button className="upload"><Upload/>Загрузить изображение</button><button className="outline wide">Библиотека дизайнов</button><label>Готовая основа <b>FPV</b></label><div className="chips"><button className="selected">FPV</button><button>Хоккей</button><button>Игры</button></div><label>Масштаб <b>{scale}%</b></label><input aria-label="Масштаб принта" type="range" min="60" max="140" value={scale} onChange={e=>setScale(+e.target.value)}/><div className="total"><span>Товар + печать</span><strong>2 690 ₽</strong><small>Точная стоимость подтвердится после проверки макета</small></div><button className="primary wide" onClick={()=>setCart(cart+1)}><ShoppingBag/>Добавить в корзину</button></aside></div></section>
    <section className="collections section" id="collections"><div className="sectionHead"><div><p className="eyebrow">ГОТОВЫЕ КОЛЛЕКЦИИ</p><h2>Начни с идеи,<br/>которая уже цепляет</h2></div><button className="outline">Смотреть HOBBY# <ArrowRight/></button></div><div className="collectionGrid">{collections.map(([n,d,icon])=><article key={n}><button aria-label={`Добавить коллекцию ${n} в избранное`} onClick={()=>setFav(!fav)}><Heart fill={fav?"currentColor":"none"}/></button><i>{icon}</i><strong>{n}</strong><span>{d}</span></article>)}</div></section>
    <section className="hobby" id="hobby"><div><p className="eyebrow lime">НОВЫЙ ДРОП</p><h2>HOBBY#</h2><p>Не просто принты. Вещи про то, чем ты живёшь: FPV, лёд, игры, музыка и скорость.</p><button className="limeButton">Смотреть коллекцию <ArrowRight/></button><button className="ghost" onClick={()=>setFav(!fav)}><Heart fill={fav?"currentColor":"none"}/>В избранное</button></div><Image src="/assets/hobby-collection.png" alt="Коллекция HOBBY" width={1200} height={480}/></section>
    <section className="benefits">{[[ShieldCheck,"Контроль качества","Проверяем каждый заказ"],[FileCheck2,"Проверка файлов","Подскажем, если нужна правка"],[Truck,"Доставка по России","СДЭК и Почта России"],[Check,"Согласование","Уточним детали до печати"]].map(([Icon,n,d]:any)=><article key={n}><Icon/><div><strong>{n}</strong><span>{d}</span></div></article>)}</section>
    <footer><div><a className="brand light" href="#"><b>пс</b><span>ПринтСелект</span></a><p>Твой принт. Твоя вещь.<br/>Наше исполнение.</p></div>{[["Покупателям","Как заказать","Доставка и оплата","Возврат и обмен"],["Каталог","Футболки","Худи","Шоперы"],["О ПринтСелект","О нас","Партнёрам","Корпоративный мерч"]].map(g=><div key={g[0]}><strong>{g[0]}</strong>{g.slice(1).map(x=><a href="#" key={x}>{x}</a>)}</div>)}<div><strong>Связаться</strong><a href="tel:88005554236">8 800 555-42-36</a><a href="mailto:hello@printselect.ru">hello@printselect.ru</a><span>Ежедневно 10:00–20:00</span></div></footer>
    {drawer&&<><div className="overlay" onClick={()=>setDrawer(null)}/><aside className="drawer"><button className="close" onClick={()=>setDrawer(null)}><X/></button>{drawer==="cart"&&<><p>Ваш заказ</p><h2>Корзина</h2>{cart?<><div className="cartItem"><Image src="/assets/tshirts/tshirt-black-front.png" alt="Товар" width={92} height={92}/><div><strong>{product}</strong><span>Чёрная · FPV</span><b>2 690 ₽ × {cart}</b></div></div><div className="drawerTotal"><span>Итого</span><strong>{(2690*cart).toLocaleString("ru-RU")} ₽</strong></div><button className="primary wide">Оформить заказ</button></>:<div className="empty"><ShoppingBag/><strong>Корзина пока пуста</strong><span>Создайте принт в конструкторе и добавьте товар.</span></div>}</>}{drawer==="favorites"&&<><p>Сохранённое</p><h2>Избранное</h2><div className="favoriteCard"><b>FLY</b><div><strong>Принт Born to Fly</strong><span>Доступно для 5 товаров</span><em>690 ₽</em></div></div><div className="favoriteCard"><b>H#</b><div><strong>Коллекция HOBBY#</strong><span>5 дизайнов в одном стиле</span><em>от 1 490 ₽</em></div></div></>}{drawer==="profile"&&<><p>Ваше пространство</p><h2>Личный кабинет</h2><h3>Создайте аккаунт</h3><span>Сохраняйте проекты и следите за статусом каждого заказа.</span><form onSubmit={e=>e.preventDefault()}><label>Имя<input placeholder="Как к вам обращаться"/></label><label>Телефон<input placeholder="+7 (___) ___-__-__"/></label><label>Email<input type="email" placeholder="name@example.ru"/></label><label>Пароль<input type="password" placeholder="Минимум 8 символов"/></label><button className="primary wide">Создать личный кабинет</button></form></>}</aside></>}
  </main>
}
